# 配置优先级
# 账号配置 (config/accounts/{qq}.yaml)
#    ↓ 未找到
# 默认配置 (config/default.yaml)
#    ↓ 未找到
# 抛出 ConfigKeyError 异常

# 可以添加账号配置来覆盖此处配置

# noon.py 模块任务配置
noon:
  华山论剑:
    战阵调整:
      # 必须设置侠士才能挑战
      # 挑战次数不区分免费和付费，每天上限40次，其中免费8次，超出即付费
      # 如果某个侠士不存在则跳过该编队挑战

      - count: 8 # 本编队挑战8次
        knights: [林朝英, 王处一, 王重阳]
      - count: 4 # 本编队挑战4次
        knights: [龙岛主, 木岛主, 笑红尘]
      # 其它编队...

    exchange: # 每月26号荣誉兑换
      6857: # id
        material_name: 钻石
        quantity: 100
      6347:
        material_name: 侠士修身录
        quantity: 0
      6348:
        material_name: 侠士手记
        quantity: 0
      6349:
        material_name: 重出江湖令
        quantity: 0
      3090:
        material_name: 斗神符
        quantity: 0

  好友:
    贡献药水:
      count: 4

  侠侣:
    情师徒拜:
      enabled: true

  群侠:
    # 如果某个侠士不存在则跳过报名
    设置战队: [林朝英, 王处一, 王重阳, 木岛主, 龙岛主]

  巅峰之战进行中:
    # id: 0 # 随机加入
    # id: 1 # 报名南派
    id: 2 # 报名北派

  矿洞:
    # 开启副本
    floor: 1 # |1 第一层|2 第二层|...|5 第五层|
    mode: 1 # |1 简单|2 普通|3 困难|

  竞技场:
    河图洛书: # 每月1~25号每天兑换10个
      enabled: true

  十二宫:
    # id: 1000 # 白羊宫
    # id: 1001 # 金牛宫
    # id: 1002 # 双子宫
    # id: 1003 # 巨蟹宫
    # id: 1004 # 狮子宫
    # id: 1005 # 处女宫
    # id: 1006 # 天秤宫
    # id: 1007 # 天蝎宫
    # id: 1008 # 射手宫
    # id: 1009 # 摩羯宫
    # id: 1010 # 水瓶宫
    id: 1011 # 双鱼宫

  历练: # 每个BOSS最多乐斗3次，每天最多5次（关闭自动使用活力药水）
    6114: 3 # 摩云山-宋姜 韦小宝碎片
    6134: 2 # 洞庭湖-大鹏 扫地僧碎片
    # 6154: 0 # 苍莽山-马大王 鹤笔翁碎片
    # 6034: 0 # 林松郊外-凶尸 令狐冲碎片
    # 6054: 0 # 林松城-虾兵头目 丁春秋碎片
    # 6074: 0 # 东海龙宫-夜叉元帅 丘处机碎片
    # 6094: 0 # 踏云镇-霹雳头领 小龙女碎片
    # 6174: 0 # 玉龙湿地-嗜血鬼王 韦一笑碎片
    # 6194: 0 # 玉龙雪山-象仙 赵敏碎片

  幻境:
    # id: 1 # 乐斗村
    # id: 2 # 林松郊外
    # id: 3 # 林松城
    # id: 4 # 东海龙宫
    # id: 5 # 踏云镇
    # id: 6 # 摩云山
    # id: 7 # 洞庭湖
    # id: 8 # 苍莽山
    # id: 9 # 玉龙湿地
    # id: 10 # 玉龙雪山
    # id: 11 # 狂沙台地
    # id: 12 # 回声遗迹
    # id: 13 # 悲叹山丘
    # id: 14 # 黄沙漩涡
    # id: 15 # 炎之洞窟
    # id: 16 # 程管小镇
    # id: 17 # 花果山
    # id: 18 # 藏剑山庄
    # id: 19 # 桃花剑冢
    id: 20 # 鹅王的试炼

  门派: # 每天门派邀请赛商店兑换一次
    门派高香:
      enabled: true
    门派战书:
      enabled: false

  门派邀请赛:
    exchange: # 周三~周日门派邀请赛商店兑换
      1246:
        material_name: 炼气石
        quantity: 0
      1247:
        material_name: 门派强化书
        quantity: 0
      1248:
        material_name: 门派高香
        quantity: 0
      1249:
        material_name: 门派战书
        quantity: 0
      1250:
        material_name: 门派引荐书
        quantity: 0

  会武:
    试炼书: # 周一、二、三试炼场试炼书不足时兑换
      enabled: true
    exchange: # 周四兑换
      1263:
        material_name: 真黄金卷轴
        quantity: 20
      1264:
        material_name: 修为丹
        quantity: 0

  梦想之旅:
    梦幻旅行: # 当已去过大于等于设置次数时消耗机票完成剩余未去过
      count: 5

  问鼎天下:
    region: 1 # 攻占东海
    # region: 2 # 攻占南荒
    # region: 3 # 攻占西泽
    # region: 4 # 攻占北寒

    # 每天总次数5（3次免费+2次付费）
    # 积分最大化是打4次1级失败+打1次3级成功：30*4+150=270
    # 攻占1级资源点次数（最多4次），3级资源点必攻占一次
    count: 2

    # 傲龙づ族℃：96690
    # 神阁☆圣域：82494
    淘汰赛: 96690 # 周六助威
    排名赛: 96690 # 周日助威

  帮派商会:
    交易会所:
      - 体力 # 交易真体力、大体力、小体力等含有体力的物品
      - 经验 # 交易经验药水、经验木筒等含有经验的物品
      # - 百炼钢 # 交易百炼钢
      # - 神来拳套 # 交易神来拳套
      # - 黄金卷轴 # 交易黄金卷轴
      # - 凤凰羽毛
      # - 潜能果实
      # - 奔流气息
      # - 投掷武器符文石
      # - 悟性丹*20
    兑换商店:
      - 泯灭·黑炎V碎片

  武林盟主:
    id: 1 # 报名黄金赛场 要求最低战力2000
    # id: 2 # 报名白银赛场 要求最低战力1000
    # id: 3 # 报名青铜赛场 要求最低战力200

  侠士客栈:
    黑市商人: # 点击 "与TA交换"，按照 "消耗xx换取xx" 格式填入
      # - 消耗斗灵石-空*66换取V级万能碎片*1
      # - 消耗黄金卷轴*3换取斗神符*1
      # - 消耗挑战书*2换取玄铁令*1
      # - 消耗斗神符*1换取淬火结晶*1
      # - 消耗门派强化书*2换取斗灵石-空*5
      # - 消耗无字天书*1换取易经八卦*1
      # - 消耗还魂丹*30换取百炼钢*1

  江湖长梦:
    exchange: # 每月20号兑换
      0: # id
        material_name: 侠士修身录
        quantity: 0
      1:
        material_name: 侠士手记
        quantity: 0
      5:
        material_name: 玄铁令
        quantity: 0
      6:
        material_name: 淬火结晶
        quantity: 0
      10:
        material_name: 真黄金卷轴
        quantity: 0
      18:
        material_name: 石中剑
        quantity: 0
      19:
        material_name: 大型武器符咒
        quantity: 0
      20:
        material_name: 中型武器符咒
        quantity: 0
      21:
        material_name: 小型武器符咒
        quantity: 0
      22:
        material_name: 投掷武器符咒
        quantity: 0

  飞升大作战:
    # 报名单排模式之前积分商城兑换一次
    # 报名双排模式之前积分商城兑换两次
    # 报名匹配模式则始终不兑换，即使设为兑换
    # 处于赛季结算中时不兑换
    玄铁令:
      enabled: true

    # 报名模式
    type: 1 # 报名单排模式；如果失败则报名匹配模式
    # type: 2 # 报名匹配模式
    # type: 3 # 报名双排模式；如果失败则报名匹配模式

    # 激活备战天赋（单、双排成功报名才能激活）
    # 激活成功或者黄金卷轴不足时结束
    id: null # 不激活
    # id: 1 # 激活燃魂决（基础）；成功率70% 消耗黄金卷轴*1 安全区外掉血减免10%
    # id: 2 # 激活燃魂决（上层）；成功率50% 消耗黄金卷轴*2 安全区外掉血减免40%
    # id: 3 # 激活燃魂决（顶层）；成功率10% 消耗黄金卷轴*3 安全区外掉血减免100%

  深渊之潮:
    深渊秘境:
      count: 0 # 兑换副本次数
      # 深渊秘境副本id
      id: 1 # 崎岖斗界
      # id: 2 # 魂渡桥
      # id: 3 # 须臾之河
      # id: 4 # 曲镜空洞
      # id: 5 # 光影迷界
      # id: 6 # 吞厄源头
      # id: 7 # 渊秘祭坛
      # id: 8 # 古帝遗迹
    exchange: # 每月20号许愿帮铺兑换
      5: # id
        material_name: 气魄之书
        quantity: 0
      6:
        material_name: 力魄之书
        quantity: 0
      7:
        material_name: 精魄之书
        quantity: 0
      8:
        material_name: 英魄之书
        quantity: 0
      9:
        material_name: 中枢之书
        quantity: 0
      10:
        material_name: 天冲之书
        quantity: 0
      11:
        material_name: 灵慧之书
        quantity: 0
      12:
        material_name: 佣兵天赋丹
        quantity: 0
      13:
        material_name: 许愿卡
        quantity: 0
      14:
        material_name: 五星许愿卡碎片
        quantity: 0
      15:
        material_name: 豆油队长碎片
        quantity: 0
      16:
        material_name: 定海制作书
        quantity: 0

  侠客岛:
    侠客行: # 如果任务包含以下奖励则接受
      - 侠士修身录*2
      # - 侠士修身录*1
      - 侠士手记*2
      # - 侠士手记*1
      # - 秘传菜谱*2
      # - 秘传菜谱*1
      # - 鉴宝真炎*2
      # - 鉴宝真炎*1
      - 太玄经*2
      - 太玄经*1
      - 玄铁令*1

  时空遗迹:
    八卦迷阵: 震巽坤离 # 如果首通有提示可以不设置
    异兽洞窟: # 依次优先扫荡否则挑战
      - 5 # 异兽母巢
      - 4 # 异兽元帅
      - 3 # 异兽将领
      - 2 # 异兽战士
      - 1 # 异兽幼崽
    exchange: # 赛季结束前一天兑换
      4: # id
        material_name: 舆图
        quantity: 40
        type: 1 # 特惠区
      8:
        material_name: 舆图
        quantity: 20
        type: 2 # 售卖区
      1:
        material_name: 日引石
        quantity: 100
        type: 1 # 特惠区
      2:
        material_name: 月引石
        quantity: 100
        type: 1 # 特惠区
      3:
        material_name: 星引石
        quantity: 100
        type: 1 # 特惠区
      5:
        material_name: 日引石
        quantity: 50
        type: 2 # 售卖区
      6:
        material_name: 月引石
        quantity: 50
        type: 2 # 售卖区
      7:
        material_name: 星引石
        quantity: 50
        type: 2 # 售卖区

  龙凰之境:
    龙凰论武:
      id: 1 # 报名龙渊赛区
      # id: 2 # 报名凰极赛区
      count: 1 # 随机挑战玩家次数，由于冷却过长只能挑战一次
    exchange: # 每月27号兑换
      1: # id
        material_name: 论武券
        quantity: 0
      2:
        material_name: 龙玉
        quantity: 0
      3:
        material_name: 凰髓
        quantity: 0
      4:
        material_name: 凰火
        quantity: 0

  我的帮派:
    帮派供奉: # 每个物品最多供奉5次
      - 3043 # 被动经验药水
      - 3014 # 经验药水
      - 3028 # 神来拳套
      - 3871 # 百炼钢
      - 3001 # 小体力
      - 3003 # 大体力
      - 3074 # 追魂锁链
      - 3089 # 还魂丹

  客栈同福:
    # 如果有指定奖励则献酒
    献酒: [王重阳碎片, 王处一碎片]

  节日福利:
    历练: # 每天反向乐斗BOSS
      enabled: true

  双旦福利:
    历练: # 每天反向乐斗BOSS
      enabled: true

  金秋福利:
    历练: # 每天反向乐斗BOSS
      enabled: true

  春节福利:
    历练: # 每天反向乐斗BOSS
      enabled: true

  多倍福利:
    历练: # 每天反向乐斗BOSS
      enabled: true

# evening.py 模块任务配置
evening:
  帮派商会:
    交易会所:
      - 体力 # 交易真体力、大体力、小体力等含有体力的物品
      - 经验 # 交易经验药水、经验木筒等含有经验的物品
      # - 百炼钢 # 交易百炼钢
      # - 神来拳套 # 交易神来拳套
      # - 黄金卷轴 # 交易黄金卷轴
      # - 凤凰羽毛
      # - 潜能果实
      # - 奔流气息
      # - 投掷武器符文石
      # - 悟性丹*20
    兑换商店:
      - 泯灭·黑炎V碎片

  侠士客栈:
    黑市商人: # 点击 "与TA交换"，按照 "消耗xx换取xx" 格式填入
      # - 消耗斗灵石-空*66换取V级万能碎片*1
      # - 消耗黄金卷轴*3换取斗神符*1
      # - 消耗挑战书*2换取玄铁令*1
      # - 消耗斗神符*1换取淬火结晶*1
      # - 消耗门派强化书*2换取斗灵石-空*5
      # - 消耗无字天书*1换取易经八卦*1
      # - 消耗还魂丹*30换取百炼钢*1

  江湖长梦:
    # 每天开启副本，消耗所有香炉，如果战败则结束回忆并跳过该副本
    # 副本要保持纯净，即没有进行中的副本，否则跳过
    # 副本优先金币

    柒承的忙碌日常:
      enabled: true
      material_name: 追忆香炉
      material_id: 6477
    群英拭剑谁为峰:
      enabled: false
      material_name: 拭剑香炉
      material_id: 6940
    时空守护者:
      enabled: false
      material_name: 时空香炉
      material_id: 6532
    倚天屠龙归我心:
      enabled: false
      material_name: 九阳香炉
      material_id: 6904
    神雕侠侣:
      enabled: false
      material_name: 盛世香炉
      material_id: 6476
    雪山藏魂:
      enabled: false
      material_name: 雪山香炉
      material_id: 8121
    桃花自古笑春风:
      enabled: false
      material_name: 桃花香炉
      material_id: 6825
    战乱襄阳:
      enabled: false
      material_name: 忠义香炉
      material_id: 6888
    天涯浪子:
      enabled: false
      material_name: 中秋香炉
      material_id: 6547
    全真古墓意难平:
      enabled: false
      material_name: 全真香炉
      material_id: 6662
    南海有岛名侠客:
      enabled: false
      material_name: 海岛香炉
      material_id: 6982
    老鹅的圣诞冒险:
      enabled: false
      material_name: 圣诞香炉
      material_id: 6609
    世外桃源梦一场:
      enabled: false
      material_name: 回梦香炉
      material_id: 6855
    中原武林之危:
      enabled: false
      material_name: 大宴香炉
      material_id: 6773
    世界树轮回秘境:
      enabled: false
      material_name: 树境香炉
      material_id: 8222
    技冠五绝:
      enabled: false
      material_name: 五绝香炉
      material_id: 8604

  深渊之潮:
    深渊秘境:
      count: 0 # 兑换副本次数
      # 深渊秘境副本id
      id: 1 # 崎岖斗界
      # id: 2 # 魂渡桥
      # id: 3 # 须臾之河
      # id: 4 # 曲镜空洞
      # id: 5 # 光影迷界
      # id: 6 # 吞厄源头
      # id: 7 # 渊秘祭坛
      # id: 8 # 古帝遗迹

  龙凰之境:
    龙凰论武:
      count: 1 # 随机挑战玩家次数，由于冷却过长只能挑战一次

  背包:
    使用: # 物品名称包含以下某个字符时会被使用
      - 盒 # 匹配仙侠盲盒、周年壕气礼盒...
      - 包 # 匹配贡献小笼包、贡献叉烧包...
      - 箱 # 匹配资源补给箱、魂珠碎片宝箱...
      - 锦囊 # 匹配惊喜锦囊、武神坛银锦囊...
      - 阅历 # 匹配阅历卷宗、阅历羊皮卷...
      - 信物 # 匹配蔡八斗的信物、吕青橙的信物...
      - 勋章 # 匹配巅峰之战一等勋章、巅峰之战二等勋章...
      - 大力丸 # 只匹配大力丸、大力丸(赠)
      - 活血散 # 只匹配活血散、活血散(赠)
      - 迅捷珠 # 只匹配迅捷珠、迅捷珠(赠)
      - 风之息 # 只匹配风之息、风之息(赠)
      - 神来拳套(赠) # 只匹配神来拳套(赠)

  吉利兑:
    exchange: # 截止日前一天兑换
      5: # id
        material_name: V级万能碎片
        quantity: 25
      6:
        material_name: 熔炼乌金
        quantity: 100
      7:
        material_name: 玄铁令
        quantity: 20
      8:
        material_name: 挑战书
        quantity: 30

  登录商店:
    # id: 1221 # 中体力*1
    # id: 1222 # 真体力*1
    # id: 1223 # 黄金卷轴*1
    # id: 1224 # 孙子兵法*1
    id: 1225 # 武穆遗书*1
    # id: 1226 # 神秘精华*1
    # id: 1227 # 神兵原石*1
    # id: 1228 # 软猥金丝*1
    # id: 1229 # 凤凰羽毛*1
    # id: 1230 # 潜能果实*1
    # id: 1231 # 上古玉髓*1
    # id: 1232 # 奔流气息*1

  儿童节:
    # id: type=1&sub_type=0 # 神兵
    # id: type=1&sub_type=1 # 神铠
    # id: type=1&sub_type=2 # 神羽
    # id: type=1&sub_type=3 # 神兽
    # id: type=1&sub_type=4 # 神饰
    # id: type=1&sub_type=5 # 神履
    # id: type=2&sub_type=0 # 坚韧不拔
    # id: type=2&sub_type=1 # 嗜血如命
    id: type=2&sub_type=2 # 坚定不移
    # id: type=2&sub_type=3 # 生存本能
    # id: type=2&sub_type=4 # 横扫千军
    # id: type=2&sub_type=5 # 三魂之力
    # id: type=2&sub_type=6 # 四魂天功
    # id: type=2&sub_type=7 # 炙血战魂
    # id: type=2&sub_type=8 # 百战之躯
    # id: type=2&sub_type=9 # 攻无不克
    # id: type=3&sub_type=0 # 投掷武器专精
    # id: type=3&sub_type=1 # 小型武器专精
    # id: type=3&sub_type=2 # 中型武器专精
    # id: type=3&sub_type=3 # 大型武器专精
    # id: type=4&sub_type=1 # 强化

  开学季:
    # id: type=1&sub_type=0 # 神兵
    # id: type=1&sub_type=1 # 神铠
    # id: type=1&sub_type=2 # 神羽
    # id: type=1&sub_type=3 # 神兽
    # id: type=1&sub_type=4 # 神饰
    # id: type=1&sub_type=5 # 神履
    # id: type=2&sub_type=0 # 坚韧不拔
    # id: type=2&sub_type=1 # 嗜血如命
    id: type=2&sub_type=2 # 坚定不移
    # id: type=2&sub_type=3 # 生存本能
    # id: type=2&sub_type=4 # 横扫千军
    # id: type=2&sub_type=5 # 三魂之力
    # id: type=2&sub_type=6 # 四魂天功
    # id: type=2&sub_type=7 # 炙血战魂
    # id: type=2&sub_type=8 # 百战之躯
    # id: type=2&sub_type=9 # 攻无不克
    # id: type=3&sub_type=0 # 投掷武器专精
    # id: type=3&sub_type=1 # 小型武器专精
    # id: type=3&sub_type=2 # 中型武器专精
    # id: type=3&sub_type=3 # 大型武器专精
    # id: type=4&sub_type=1 # 强化

  生肖福卡:
    QQ: null # 用于向好友分享一个福卡

  客栈同福:
    # 如果有指定奖励则献酒
    献酒: [王重阳碎片, 王处一碎片]

  节日福利:
    斗神塔:
      count: 16

  双旦福利:
    斗神塔:
      count: 16

  金秋福利:
    斗神塔:
      count: 16

  春节福利:
    斗神塔:
      count: 16

  多倍福利:
    斗神塔:
      count: 16

  微信兑换:
    兑换码: 265151

  春联大赛:
    爆竹传吉语: 腊梅报新春
    爆竹欣祝福: 银蛇喜迎春
    爆竹欣祝褔: 银蛇乐报春
    春呈丰稔景: 酒贺小龙年
    春到田畴绿: 蛇来淑景新
    春归蛇起舞: 福到鸟争鸣
    春来千野绿: 蛇舞四时新
    除牙难捕鼠: 添足便成龙
    丁年歌盛世: 卯兔耀中华
    国强民幸福: 蛇舞世升平
    红梅迎春笑: 玉兔出月欢
    红梅迎雪放: 玉兔踏春来
    红梅赠虎岁: 彩烛耀兔年
    花放山河丽: 蛇迎世纪春
    花开四季馥: 蛇舞九州春
    花柳春风绿: 蛇年瑞气盈
    虎辟长安道: 兔开大吉春
    虎驰金世界: 兔唤玉乾坤
    虎带祥云去: 兔铺锦绣来
    虎年腾大步: 兔岁展宏图
    虎去雄风在: 兔来喜气浓
    虎声传捷报: 兔影抖春晖
    虎嘶飞雪里: 兔舞画图中
    虎蹄留胜迹: 兔角搏青云
    虎威惊盛世: 兔翰绘新春
    虎跃前程去: 兔携好运来
    虎留英雄气: 兔会世纪风
    捷报飞新宇: 春潮促小龙
    捷报书宏志: 春风乐小龙
    金虎辞旧岁: 银兔贺新春
    金蛇含瑞草: 紫燕报新春
    金蛇狂舞日: 紫燕报春时
    金蛇盘玉兔: 赤帜舞神州
    睛点龙飞去: 珠还蛇舞来
    龙去神威在: 蛇来紫气生
    龙蛇交替舞: 岁月又更新
    龙腾传捷报: 蛇舞兆丰年
    龙腾丰稔岁: 蛇舞吉庆年
    龙舞山河壮: 蛇盘世纪新
    龙吟山海壮: 蛇舞国民欢
    龙展强邦志: 蛇生富国情
    卯来四季美: 兔献百家福
    卯门生紫气: 兔岁报拜年
    卯时春入户: 兔岁喜盈门
    民逢大有岁: 国正小龙年
    瑞雪兆丰年: 迎得玉兔归
    山舞银蛇景: 梅香瑞雪春
    山舞银蛇日: 地披红杏时
    蛇酿新年酒: 花开盛世春
    蛇舞升平世: 莺歌富贵春
    笙歌辞旧岁: 兔酒庆新春
    兔归皓月亮: 花绽春光妍
    兔毫抒壮志: 燕梭织春光
    兔俊千山秀: 春暖万水清
    喜迎新世纪: 欢庆小龙年
    雪消狮子瘦: 月满兔儿肥
    燕舞春光丽: 兔奔曙光新
    寅年春锦绣: 卯序业辉煌
    玉兔蟾宫笑: 红梅五岭香
    玉兔迎春到: 红梅祝福来
    玉兔迎春至: 黄莺报喜来
    Q宠驭马闯新春: 侠士跟随巡江湖
    爆风逐蛇巡乐斗: 剑圣驱马守江山
    辞蛇年八方进宝: 迎马年四季发财
    辞蛇岁乐斗兴旺: 迎马年江湖昌隆
    鹅游乐斗随金蛇: 客聚江湖伴玉骢
    发财鹅迎蛇送福: 福马鹅接马添欢
    福马鹅驰追蛇影: 发财鹅跃逐马蹄
    金蛇点兵召佣兵: 福马点将唤神将
    金蛇启岁临乐斗: 福马迎春踏江川
    金蛇启运乐斗兴: 福马开泰江湖旺
    剑圣鹅随蛇辞旧: 精灵鹅伴马迎新
    乐斗聚贤逢蛇岁: 江湖结义遇马年
    龙脊承蛇安大陆: 蛇矛御马定江山
    灵蛇绕陆贺新岁: 神驹游湖庆吉年
    灵蛇佑侠平安岁: 骏马护将吉祥年
    青蛇点墨书新景: 白马挥毫绘锦天
    蛇矛映雪辉乐斗: 神弓凝霜耀江天
    蛇盘乐斗开鸿运: 马跃江湖纳吉缘
    蛇辞旧岁歌乐斗: 马迎新春笑江天
    蛇辞旧岁器魂盛: 马迎新春战力强
    蛇绕神弓呈吉兆: 马依龙脊展宏图
    蛇舞核弹惊天地: 马驰龙脊震乐斗
    蛇舞江湖凝器魂: 马驰乐斗聚侠心
    蛇游乐斗寻知己: 马走江湖结善缘
    神将摆摊卖撸串: 佣兵唠嗑送神装
    巳蛇纳福发财鹅: 午马迎祥福马鹅
    巳蛇送吉满大陆: 午马迎禧遍乐斗
    笑红尘歌蛇报喜: 福马鹅舞马呈安
    笑红尘随蛇纳福: 发财鹅伴马迎祥
    玉蛇衔福临洲岸: 金马驮祥踏浪澜

  爱的同心结:
    QQ: # 用于向好友赠送一个同心结
      # - QQ1
      # - QQ2
